spring:
  application:
    name: auth-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      username: ${CONFIG_SERVER_USER:ihs}
      password: ${CONFIG_SERVER_PASS:ihs123!}
    openfeign:
      circuitbreaker:
        enabled: false
      okhttp:
        enabled: false
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
            loggerLevel: basic
app:
  x-api-key: "X_API_KEY"

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, circuitbreakers, circuitbreakerevents
  health:
    circuitbreakers:
      enabled: true

customer-service:
  url: http://localhost:8082

resilience4j:
  circuitbreaker:
    instances:
      CustomerFeignClient:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
  timelimiter:
    instances:
      CustomerFeignClient:
        timeoutDuration: 4s