spring:
  application:
    name: customer-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      username: ${CONFIG_SERVER_USER:ihs}
      password: ${CONFIG_SERVER_PASS:ihs123!}
    openfeign:
      circuitbreaker:
        enabled: true
      okhttp:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
            loggerLevel: basic

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, circuitbreakers, circuitbreakerevents
  health:
    circuitbreakers:
      enabled: true

currency-service:
  url: http://localhost:8081

resilience4j:
  circuitbreaker:
    instances:
      CurrencyClient:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
  timelimiter:
    instances:
      CurrencyClient:
        timeoutDuration: 4s