spring:
  application:
    name: customer-product-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      username: ${CONFIG_SERVER_USER:ihs}
      password: ${CONFIG_SERVER_PASS:ihs123!}
    openfeign:
      circuitbreaker:
        enabled: false
      okhttp:
        enabled: false
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
            loggerLevel: basic
  temporal:
    connection:
      target: ${TEMPORAL_TARGET:127.0.0.1:7233}
    namespace: ${TEMPORAL_NAMESPACE:default}

server:
  port: 8084

app:
  x-api-key: "X_API_KEY"

saga-service:
  url: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, circuitbreakers, circuitbreakerevents
  health:
    circuitbreakers:
      enabled: true
